//! ADR 0011 — property tests for the v7.0 rsync hybrid transport
//! wire codec.
//!
//! These tests fuzz the deterministic encode/decode contracts of
//! every public codec under `src/adapters/rsync/wire/` against the
//! `MplexReader` / `MplexWriter` / `tokio::io::duplex` round-trip
//! pattern already used by the in-module unit tests:
//!
//! 1. `prop_flist_round_trip_proto31` — random `Vec<Flist>` (regular
//!    files only) round-trips through `send_flist` / `recv_flist`
//!    against the proto-31 16-bit `XMIT_EXTENDED_FLAGS` wire shape.
//! 2. `prop_flist_round_trip_proto27` — same property against the
//!    8-bit `FLIST_*` proto-27 wire shape.
//! 3. `prop_ndx_round_trip` — random `Vec<i32>` (positive +
//!    `NDX_DONE`) round-trips through `write_ndx` / `read_ndx` at
//!    proto 31, preserving the diff-encoded sequence.
//! 4. `prop_hash_split_combine_inverse` — `hash_fast(buf)` equals
//!    `combine_s1_s2(hash_split(buf))` for arbitrary `Vec<u8>`.
//! 5. `prop_hash_roll_matches_recompute` — rolling-window slide via
//!    `hash_roll` agrees with a fresh `hash_fast` over the new
//!    window for arbitrary buffers + window sizes.
//! 6. `prop_file_hasher_md5_proto31_matches_streaming` —
//!    `FileHasher::for_protocol(seed, 31)` produces
//!    `MD5(file_bytes)` regardless of seed for arbitrary chunked
//!    buffers.
//! 7. `prop_file_hasher_md4_proto27_seed_dependent` —
//!    `FileHasher::for_protocol(seed, 27)` produces
//!    `MD4(seed_le || file_bytes)` and is seed-sensitive.
//! 8. `prop_mplex_data_frame_round_trip` — arbitrary byte buffers
//!    survive the mplex `MSG_DATA` framing layer (header chunking
//!    capped at `MAX_PAYLOAD_LEN`).
//!
//! Run with:
//!
//! ```text
//! cargo test --features test-fixtures --test property_rsync
//! ```

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::cast_possible_truncation,
    clippy::cast_lossless,
    clippy::cast_sign_loss,
    clippy::cast_possible_wrap,
    clippy::module_name_repetitions,
    clippy::default_numeric_fallback,
    clippy::wildcard_imports,
    clippy::needless_pass_by_value,
    reason = "property tests use unwrap and proptest macros that pull broad imports — strict suppressions apply only to the test target"
)]

use std::path::PathBuf;

use proptest::collection::vec as prop_vec;
use proptest::prelude::*;
use ssh_mcp::adapters::rsync::wire::flist::{
    Flist, FlistRecvOpts, FlistSendOpts, recv_flist, send_flist,
};
use ssh_mcp::adapters::rsync::wire::hash::{
    FileHasher, combine_s1_s2, hash_fast, hash_roll, hash_split,
};
use ssh_mcp::adapters::rsync::wire::io::{MplexReader, MplexTag, MplexWriter};
use ssh_mcp::adapters::rsync::wire::ndx::{NDX_DONE, NdxState, read_ndx, write_ndx};
use ssh_mcp::adapters::rsync::wire::session::WireSession;
use tokio::io::duplex;
use tokio::runtime::Builder;

// ---------------------------------------------------------------------------
// Strategy helpers
// ---------------------------------------------------------------------------

/// POSIX regular-file mode bits — `S_IFREG | 0o0644` is the canonical
/// shape every entry generated by the strategy carries.
const REG_MODE: u32 = 0o100_644;

/// Bound for byte-buffer fuzzing — keeps round-trip times under the
/// proptest 256-case budget reasonable on CI.
const MAX_BUF_LEN: usize = 256;

/// Strategy: a single non-empty POSIX path with letters + digits +
/// `/`. Avoids `..` and absolute prefixes — those would trip the
/// receiver-side security check ported from openrsync.
fn arb_safe_path() -> impl Strategy<Value = PathBuf> {
    "[a-z0-9]{1,8}(/[a-z0-9]{1,8}){0,3}".prop_map(PathBuf::from)
}

/// Strategy: a regular-file [`Flist`] entry with deterministic mode +
/// random size / mtime / uid / gid.
fn arb_flist_regular() -> impl Strategy<Value = Flist> {
    (
        arb_safe_path(),
        0_i64..=(1_i64 << 32),
        0_i64..=2_000_000_000_i64,
        0_u32..=65_535,
        0_u32..=65_535,
    )
        .prop_map(|(path, size, mtime, uid, gid)| {
            Flist::regular(path, size, mtime, REG_MODE, uid, gid)
        })
}

/// Strategy: a small `Vec<Flist>` of unique-path regular files.
/// Duplicate paths are filtered post-generation because the receiver
/// would deduplicate them via openrsync's `qsort` + uniqueness pass.
fn arb_flist_vec() -> impl Strategy<Value = Vec<Flist>> {
    prop_vec(arb_flist_regular(), 1..=8).prop_filter("non-unique paths", |entries| {
        let mut paths: Vec<&PathBuf> = entries.iter().map(|e| &e.path).collect();
        paths.sort();
        paths.dedup();
        paths.len() == entries.len()
    })
}

/// Strategy: arbitrary byte buffer for hash + mplex round-trip
/// fuzzing.
fn arb_byte_buf() -> impl Strategy<Value = Vec<u8>> {
    prop_vec(any::<u8>(), 0..=MAX_BUF_LEN)
}

/// Strategy: ascending sequence of positive ndx values (mirrors the
/// rsync sender's natural access pattern). The diff-encoder is
/// optimised for this access pattern and any random sequence would
/// bloat the wire to test a path that is not exercised in practice.
fn arb_ndx_ascending() -> impl Strategy<Value = Vec<i32>> {
    prop_vec(0_i32..=10_000, 0..=16).prop_map(|deltas| {
        let mut out = Vec::with_capacity(deltas.len());
        let mut acc = 0_i32;
        for d in deltas {
            // Diff must be >= 1 so the index strictly increases (the
            // codec encodes `diff = ndx - prev` and the proto-30 wire
            // shape collapses `diff == 0` ambiguously to a stale
            // `prev_positive`).
            acc = acc.saturating_add(d.saturating_add(1));
            out.push(acc);
        }
        out
    })
}

// ---------------------------------------------------------------------------
// Properties
// ---------------------------------------------------------------------------

/// Build a single-shot tokio runtime so the proptest harness can
/// drive `async` futures from a synchronous test body.
fn run_async<F, T>(future: F) -> T
where
    F: std::future::Future<Output = T>,
{
    Builder::new_current_thread()
        .enable_time()
        .build()
        .expect("rt build")
        .block_on(future)
}

/// Round-trip a `Vec<Flist>` through `send_flist` / `recv_flist` at
/// the given negotiated protocol version. Returns the decoded entries
/// for caller comparison.
///
/// Uses matched send + recv opts that preserve uids + gids so the
/// round-trip exercises the full per-entry shape — without preserve
/// flags the codec drops the owner fields per the upstream rsync
/// `--owner` / `--group` contract.
async fn flist_round_trip(entries: &[Flist], proto: i32) -> Vec<Flist> {
    let (left, right) = duplex(64 * 1024);
    let (lr, lw) = tokio::io::split(left);
    let (rr, _rw) = tokio::io::split(right);
    drop(lr);
    let mut writer = MplexWriter::new(lw);
    let mut sess_w = WireSession::new();
    sess_w.negotiated = proto;
    let send_opts = FlistSendOpts {
        preserve_uids: true,
        preserve_gids: true,
        preserve_links: false,
    };
    let recv_opts = FlistRecvOpts {
        preserve_uids: true,
        preserve_gids: true,
        preserve_links: false,
    };
    send_flist(&mut writer, &mut sess_w, entries, send_opts, proto)
        .await
        .expect("send_flist ok");

    let mut reader = MplexReader::new(rr);
    let mut sess_r = WireSession::new();
    sess_r.negotiated = proto;
    recv_flist(&mut reader, &mut sess_r, recv_opts, proto)
        .await
        .expect("recv_flist ok")
}

/// Compare two flist entries on the fields the codec preserves.
///
/// `flags` is excluded because the encoder strips everything except
/// `FLIST_TOP_LEVEL`; `link` is excluded because the strategy
/// generates regular files only (no symlink target). `mode` and `uid`
/// / `gid` are compared verbatim.
fn assert_flist_equal(decoded: &Flist, original: &Flist) -> Result<(), TestCaseError> {
    prop_assert_eq!(&decoded.path, &original.path, "path drift");
    prop_assert_eq!(decoded.size, original.size, "size drift");
    prop_assert_eq!(decoded.mtime, original.mtime, "mtime drift");
    prop_assert_eq!(decoded.mode, original.mode, "mode drift");
    prop_assert_eq!(decoded.uid, original.uid, "uid drift");
    prop_assert_eq!(decoded.gid, original.gid, "gid drift");
    Ok(())
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    /// `prop_flist_round_trip_proto31`
    ///
    /// Random `Vec<Flist>` regular-file entries round-trip through
    /// the proto-31 `XMIT_EXTENDED_FLAGS` wire shape.
    #[test]
    fn prop_flist_round_trip_proto31(entries in arb_flist_vec()) {
        let decoded = run_async(flist_round_trip(&entries, 31));
        prop_assert_eq!(decoded.len(), entries.len(), "entry count drift");
        for (i, (got, want)) in decoded.iter().zip(entries.iter()).enumerate() {
            assert_flist_equal(got, want)
                .map_err(|e| TestCaseError::fail(format!("entry {i}: {e}")))?;
        }
    }

    /// `prop_flist_round_trip_proto27`
    ///
    /// Same property against the legacy 8-bit `FLIST_*` wire shape
    /// (no `XMIT_EXTENDED_FLAGS` high byte; `write_int` lengths
    /// rather than varint).
    #[test]
    fn prop_flist_round_trip_proto27(entries in arb_flist_vec()) {
        let decoded = run_async(flist_round_trip(&entries, 27));
        prop_assert_eq!(decoded.len(), entries.len(), "entry count drift");
        for (i, (got, want)) in decoded.iter().zip(entries.iter()).enumerate() {
            assert_flist_equal(got, want)
                .map_err(|e| TestCaseError::fail(format!("entry {i}: {e}")))?;
        }
    }

    /// `prop_ndx_round_trip`
    ///
    /// Ascending positive index sequences plus a trailing
    /// `NDX_DONE` round-trip through the proto-31 diff codec without
    /// drift.
    #[test]
    fn prop_ndx_round_trip(values in arb_ndx_ascending()) {
        run_async(async move {
            let (left, right) = duplex(4 * 1024);
            let (lr, lw) = tokio::io::split(left);
            let (rr, _rw) = tokio::io::split(right);
            drop(lr);
            let mut writer = MplexWriter::new(lw);
            let mut sess_w = WireSession::new();
            let mut state_w = NdxState::new();
            for ndx in &values {
                write_ndx(&mut writer, &mut sess_w, &mut state_w, 31, *ndx)
                    .await
                    .expect("write_ndx ok");
            }
            write_ndx(&mut writer, &mut sess_w, &mut state_w, 31, NDX_DONE)
                .await
                .expect("write_ndx done ok");

            let mut reader = MplexReader::new(rr);
            let mut sess_r = WireSession::new();
            let mut state_r = NdxState::new();
            for expected in &values {
                let got = read_ndx(&mut reader, &mut sess_r, &mut state_r, 31)
                    .await
                    .expect("read_ndx ok");
                assert_eq!(got, *expected, "ndx drift");
            }
            let done = read_ndx(&mut reader, &mut sess_r, &mut state_r, 31)
                .await
                .expect("read_ndx done");
            assert_eq!(done, NDX_DONE, "missing NDX_DONE sentinel");
        });
    }

    /// `prop_hash_split_combine_inverse`
    ///
    /// `hash_split` followed by `combine_s1_s2` reproduces the same
    /// packed `u32` `hash_fast` returns for any byte buffer.
    #[test]
    fn prop_hash_split_combine_inverse(buf in arb_byte_buf()) {
        let direct = hash_fast(&buf);
        let (s1, s2) = hash_split(&buf);
        let combined = combine_s1_s2(s1, s2);
        prop_assert_eq!(direct, combined, "hash_split/combine round-trip drift");
    }

    /// `prop_hash_roll_matches_recompute`
    ///
    /// Sliding the rolling-hash window by one byte produces the same
    /// `(s1, s2)` that fresh `hash_split` over the new window window
    /// returns. Buffers shorter than the window are skipped (the
    /// rolling hash is undefined there).
    #[test]
    fn prop_hash_roll_matches_recompute(
        buf in arb_byte_buf().prop_filter("len >= 5", |b| b.len() >= 5),
        block_len_seed in 2_u32..=4,
    ) {
        let block_len = block_len_seed.min(u32::try_from(buf.len()).unwrap_or(2)) - 1;
        prop_assume!(block_len >= 2);
        let block_len_us = usize::try_from(block_len).unwrap_or(2);
        prop_assume!(buf.len() > block_len_us);

        let (mut s1, mut s2) = hash_split(&buf[0..block_len_us]);
        // Slide the window across the whole buffer.
        let max_offset = buf.len() - block_len_us;
        for offset in 1..=max_offset {
            let out_byte = buf[offset - 1];
            let in_byte = if offset + block_len_us - 1 < buf.len() {
                Some(buf[offset + block_len_us - 1])
            } else {
                None
            };
            let (n1, n2) = hash_roll(s1, s2, out_byte, in_byte, block_len);
            s1 = n1;
            s2 = n2;
            if let Some(_byte_in) = in_byte {
                let combined = combine_s1_s2(s1, s2);
                let expected = hash_fast(&buf[offset..offset + block_len_us]);
                prop_assert_eq!(
                    combined,
                    expected,
                    "rolling hash drift at offset {}",
                    offset
                );
            }
        }
    }

    /// `prop_file_hasher_md5_proto31_matches_streaming`
    ///
    /// At negotiated protocol 31 the per-file digest is plain MD5
    /// regardless of seed. The proptest splits the buffer at a
    /// random point to exercise the streaming `update` API.
    #[test]
    fn prop_file_hasher_md5_proto31_matches_streaming(
        buf in arb_byte_buf(),
        seed in any::<i32>(),
        split_at in any::<u8>(),
    ) {
        use md5::{Digest, Md5};
        let split = usize::from(split_at) % buf.len().max(1);
        let mut hasher = FileHasher::for_protocol(seed, 31);
        let (head, tail) = buf.split_at(split.min(buf.len()));
        hasher.update(head);
        hasher.update(tail);
        let got = hasher.finish();
        let mut want = Md5::new();
        Md5::update(&mut want, &buf);
        let want_d = want.finalize();
        prop_assert_eq!(&got[..], want_d.as_slice());
    }

    /// `prop_file_hasher_md4_proto27_seed_dependent`
    ///
    /// At negotiated protocol 27 the per-file digest is MD4 with the
    /// session seed prefixed in little-endian. Different seeds must
    /// produce different digests for the same content.
    #[test]
    fn prop_file_hasher_md4_proto27_seed_dependent(
        buf in arb_byte_buf().prop_filter("non-empty", |b| !b.is_empty()),
        seed_a in any::<i32>(),
        seed_b in any::<i32>(),
    ) {
        prop_assume!(seed_a != seed_b);
        let mut h_a = FileHasher::for_protocol(seed_a, 27);
        h_a.update(&buf);
        let d_a = h_a.finish();
        let mut h_b = FileHasher::for_protocol(seed_b, 27);
        h_b.update(&buf);
        let d_b = h_b.finish();
        prop_assert_ne!(d_a, d_b, "MD4 digests collided across distinct seeds");
    }

    /// `prop_mplex_data_frame_round_trip`
    ///
    /// Arbitrary byte buffers survive the mplex `MSG_DATA` framing
    /// layer end-to-end. Exercises `write_buf` chunking and
    /// `read_buf` reassembly across whatever frame boundary the
    /// encoder picks.
    #[test]
    fn prop_mplex_data_frame_round_trip(buf in arb_byte_buf()) {
        run_async(async move {
            let (left, right) = duplex(64 * 1024);
            let (lr, lw) = tokio::io::split(left);
            let (rr, _rw) = tokio::io::split(right);
            drop(lr);
            let mut writer = MplexWriter::new(lw);
            let mut sess_w = WireSession::new();
            sess_w.mplex_writes = true;
            writer
                .write_buf(&mut sess_w, &buf)
                .await
                .expect("write_buf ok");
            let mut reader = MplexReader::new(rr);
            let mut sess_r = WireSession::new();
            sess_r.mplex_reads = true;
            let mut out = vec![0_u8; buf.len()];
            if !out.is_empty() {
                reader
                    .read_buf(&mut sess_r, &mut out)
                    .await
                    .expect("read_buf ok");
            }
            assert_eq!(out, buf, "mplex round-trip drift");
        });
    }

    /// `prop_mplex_tag_wire_byte_round_trip`
    ///
    /// Every `MplexTag` variant survives the `to_wire` /
    /// `from_wire` round-trip — including the `Unknown(byte)`
    /// fallback for arbitrary unbiased bytes.
    #[test]
    fn prop_mplex_tag_wire_byte_round_trip(byte in any::<u8>()) {
        let tag = MplexTag::from_wire(byte);
        let back = tag.to_wire();
        prop_assert_eq!(back, byte, "MplexTag wire byte round-trip drift");
    }
}
